name: Codacy Analysis CLI

on: ["push"]

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          # tool: <CLIENT_SIDE_TOOL_NAME>
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647
      - name: set-up go
        uses: actions/setup-go@v3
        with:
          # Go version currently supported by Codacy
          go-version: 1.19.1
          run-gosec: "true"
          run-staticcheck: "true"
          clang-tidy-output: "path/to/output"
          faux-pas-output: "path/to/output"
          run-docker-tools: "false"
